nncmpp
======

'nncmpp' is yet another MPD client.  It does exactly what I want it to, more
specifically it's a simplified TUI version of Sonata so that I don't need to
run an ugly undeveloped Python application.

If it's not obvious enough, the name a pun on all those ridiculous client names,
and should be pronounced as "nincompoop".

Currently it's under development and doesn't work in any sense yet.

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR, or from
openSUSE Build Service for the rest of mainstream distributions.  Consult the
list of repositories and their respective links at:

https://build.opensuse.org/project/repositories/home:pjanouch:git

Building and Running
--------------------
Build dependencies: CMake, pkg-config, liberty (included), termo (included) +
Runtime dependencies: ncursesw, libunistring

 $ git clone --recursive https://github.com/pjanouch/nncmpp.git
 $ mkdir nncmpp/build
 $ cd nncmpp/build
 $ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
 $ make

To install the application, you can do either the usual:

 # make install

Or you can try telling CMake to make a package for you.  For Debian it is:

 $ cpack -G DEB
 # dpkg -i nncmpp-*.deb

Note that for versions of CMake before 2.8.9, you need to prefix `cpack` with
`fakeroot` or file ownership will end up wrong.

Having the program installed, create a configuration file and run it.

Configuration
-------------
Create _~/.config/nncmpp/nncmpp.conf_ with contents like the following:

....
settings = {
	address = "localhost"
	password = "<your password>"
	root = "~/Music"
}
colors = {
	header = "reverse"
	header_active = "underline"
	even = "16 231"
	odd = "16 255"
}
....

Contributing and Support
------------------------
Use this project's GitHub to report any bugs, request features, or submit pull
requests.  If you want to discuss this project, or maybe just hang out with
the developer, feel free to join me at irc://irc.janouch.name, channel #dev.

License
-------
'nncmpp' is written by Přemysl Janouch <p.janouch@gmail.com>.

You may use the software under the terms of the ISC license, the text of which
is included within the package, or, at your option, you may relicense the work
under the MIT or the Modified BSD License, as listed at the following site:

http://www.gnu.org/licenses/license-list.html
