# Public Domain

find_path (UNISTRING_INCLUDE_DIRS unistr.h)
find_library (UNISTRING_LIBRARIES NAMES unistring libunistring)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (UNISTRING DEFAULT_MSG
	UNISTRING_INCLUDE_DIRS UNISTRING_LIBRARIES)

mark_as_advanced (UNISTRING_LIBRARIES UNISTRING_INCLUDE_DIRS)
